train:
    batch_size: 64
    test_batch_size: 100
    lr: 0.001
    use_cuda: True
    seed : 1
    epochs: 70
    log_interval: 20
    log: outputs/usps2mnist.log
    pretrained_path: pytorch_model_usps2mnist
    train_data_a: USPSSAMPLE
    train_data_a_path: data/uspssample
    train_data_a_size: 7438
    train_data_a_seed: 0
    train_data_a_use_train_data: True
    train_data_b: MNISTSAMPLE
    train_data_b_path: data/mnistsample
    train_data_b_size: 60000
    train_data_b_seed: 0
    train_data_b_use_train_data: True
    test_data_b: MNISTSAMPLE
    test_data_b_path: data/mnistsample
    test_data_b_size: 10000
    test_data_b_seed: 0
    test_data_b_use_train_data: False
